### ISSUE TITLE
Make combinatorics classes more Stream friendly

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Test-Framework#24]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Test-Framework-2.23ea4](https://github.com/OpenHFT/Chronicle-Test-Framework/releases/chronicle-test-framework-2.23ea4), [BOM-2.23ea70](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea70)
