### ISSUE TITLE
Expose ExceptionTracker as public API

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Test-Framework#36]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Test-Framework-2.24ea5](https://github.com/OpenHFT/Chronicle-Test-Framework/releases/chronicle-test-framework-2.24ea5), [BOM-2.24ea73](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea73)
