### ISSUE TITLE
TcpProxyTest fails every time on Mac

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Test-Framework#38]
[TC run](https://teamcity.chronicle.software/buildConfiguration/Chronicle_ChronicleTestFramework_SnapshotMac?mode=builds#all-projects)

It would fail even in known good `2.24ea4` release so it's something about Agent configuration or Java version.

**Comment by RobAustin** [comment]
it now working, both locally and on TC

<img width="1472" alt="image" src="https://github.com/OpenHFT/Chronicle-Test-Framework/assets/6506056/15aeaaad-0302-43c3-ab07-f98e011850dd">

and locally

<img width="1259" alt="image" src="https://github.com/OpenHFT/Chronicle-Test-Framework/assets/6506056/cf363ef1-d819-47b9-a104-412fc43c94e0">
