### ISSUE TITLE
Add metrics for exposed API surface

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Test-Framework#6]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Test-Framework-1.22ea4](https://github.com/OpenHFT/Chronicle-Test-Framework/releases/chronicle-test-framework-1.22ea4), [BOM-2.22ea71](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea71)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Test-Framework-1.22ea4](https://github.com/OpenHFT/Chronicle-Test-Framework/releases/chronicle-test-framework-1.22ea4), [BOM-2.22ea72](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea72)
